#!/usr/bin/env bash

set -e

cd /var/lib/ssh/cache/repo
git pull

CLASS_FILE='/var/lib/ssh/classes'
if [[ ! -e $CLASS_FILE ]] ; then
    echo 'strong' > $CLASS_FILE
fi
CLASSES="$(cat $CLASS_FILE)"
for class in $CLASSES ; do
    find "$class" -mindepth 1 -type f -exec cat {} \; 2>/dev/null | tee ../keys
done

